### ISSUE TITLE
Please remove completely annoying checkstyle import checks

### ISSUE THREAD

**Issue by fabian-schlegel** [kokuwaio/maven-parent#13]
Remove this annoying and illogical import ordering check or at least provide a proper formatter file for Idea / Eclipse IDEs so the checks can somehow be fulfilled.

**Comment by stephanschnabel** [comment]
I've added the files for eclipse, esp [importorder](https://github.com/kokuwaio/maven-parent/commit/6b26158778ad9d6163de2e2a889c78017c485b87#diff-1e62fd8f748d831696b0aa62c99dd8b0ecf9ea33dcd19becb2a1ace76d7b7e16), for Idea this is correct: [ https://stackoverflow.com/questions/14716283](https://stackoverflow.com/questions/14716283/is-it-possible-for-intellij-to-)organize-imports-the-same-way-as-in-eclipse/17194980#17194980)

**Comment by stephanschnabel** [comment]
I've added the files for eclipse, esp [importorder](https://github.com/kokuwaio/maven-parent/commit/6b26158778ad9d6163de2e2a889c78017c485b87#diff-1e62fd8f748d831696b0aa62c99dd8b0ecf9ea33dcd19becb2a1ace76d7b7e16), for Idea this is correct: [ https://stackoverflow.com/questions/14716283](https://stackoverflow.com/questions/14716283/is-it-possible-for-intellij-to-organize-imports-the-same-way-as-in-eclipse/17194980#17194980)

**Comment by stephanschnabel** [comment]
Close due lack of response.
